import Head from 'next/head'
import Header from '../components/header'

function Search() {

    return <div>

        <Head>
        <title>Search Results</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="googleTitleIcon.ico" />    
        </Head>

        {/* Header */}
        <Header />

        
    </div>


}

export default Search;