import Head from "next/head";
import Header from "../components/header";
import Response from "../keys";
import { useRouter } from "next/router";
import SearchResults from "../components/SearchResults";

import {API_KEY, CONT_KEY} from "../keys"



function Search({ results }) {
  const router = useRouter();

  console.log(results);

  return (
    <div>
      <Head>
        <title>{router.query.term} - Google Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="googleTitleIcon.ico" />
      </Head>

      <Header />

      <SearchResults results={results} />
    </div>
  );
}

export default Search;

export async function getServerSideProps(context) {
  const useDummyData = false;
  const startIndex = context.query.start || 0;

  const data = useDummyData
    ? Response
    : await fetch(
        `https://www.googleapis.com/customsearch/v1?key=${API_KEY}&cx=${CONT_KEY}&q=${context.query.term}&start=${startIndex}
    `
      ).then((response) => response.json());

  //After results has rendered.. pass the results to the clients
  return {
    props: {
      results: data,
    },
  };
}

